#!/usr/bin/env bash

BASE="/home/judge/hw4/4-1"
SRC="${BASE}/src"
DATA="${BASE}/data"
PYTHON="${BASE}/.venv/bin/python3"

while getopts "d:p:u:" opt; do
    case "${opt}" in
    d)
        # modify caddyfile
        echo "DOMAIN: '${OPTARG}'"
        DOMAIN="${OPTARG}"
        ;;
    p)
        # store jwt secret
        echo "SECRET: '${OPTARG}'"
        echo "${OPTARG}" > "${DATA}/secret"
        ;;
    u)
        # store user information
        echo "USER: '${OPTARG}'"
        users+=("${OPTARG}")
        ;;
    esac
done

echo "${users[@]}" | tr ' ' '\n' | tr ':' ' ' > "${DATA}/users"

# Change domain
sed "s/<DOMAIN>/${DOMAIN}/g" "${DATA}/Caddyfile.sample" > "${DATA}/Caddyfile"

# Reload config
caddy reload --adapter caddyfile --config "${DATA}/Caddyfile"

# setup domain
sudo sed -i "" "s/[a-zA-Z0-9-]*.28.nasa.nycu/${DOMAIN}/" /etc/hosts

# check server status
until curl "https://${DOMAIN}"; do
    echo "* Server is starting..."
done
